name: Bazaar
version: 3.0
main: de.ancash.bazaar.Bazaar
depend: [ILibrary, Vault]

commands:
   bz:
      description: Various options for interacting with the plugin
      usage: Please use /bz <open>