name: Bazaar
version: 4.3
main: de.ancash.bazaar.Bazaar
depend: [ILibrary, Vault]
api-version: 1.13

commands:
   bz:
      description: Many (2) options for interacting with the plugin
      usage: Use /bz <open, setitem> <player>